#pragma once

#include <SDL2/SDL.h>

namespace Tabby {
using GamepadAxis = int32_t;
using GamepadButtons = uint32_t;

namespace Gamepad {

    namespace Axis {
        enum : GamepadAxis {
            GAMEPAD_AXIS_LEFT_X = 0,
            GAMEPAD_AXIS_LEFT_Y = 1,
            GAMEPAD_AXIS_RIGHT_X = 2,
            GAMEPAD_AXIS_RIGHT_Y = 3,
            GAMEPAD_AXIS_LEFT_TRIGGER = 4,
            GAMEPAD_AXIS_RIGHT_TRIGGER = 5
        };
    }

    namespace Buttons {
        enum : GamepadButtons {
            GAMEPAD_BUTTON_RIGHT_FACE_UP = SDL_CONTROLLER_BUTTON_Y,
            GAMEPAD_BUTTON_RIGHT_FACE_RIGHT = SDL_CONTROLLER_BUTTON_B,
            GAMEPAD_BUTTON_RIGHT_FACE_DOWN = SDL_CONTROLLER_BUTTON_A,
            GAMEPAD_BUTTON_RIGHT_FACE_LEFT = SDL_CONTROLLER_BUTTON_X,

            GAMEPAD_BUTTON_LEFT_SHOULDER = SDL_CONTROLLER_BUTTON_LEFTSHOULDER,
            GAMEPAD_BUTTON_RIGHT_SHOULDER = SDL_CONTROLLER_BUTTON_RIGHTSHOULDER,
            GAMEPAD_BUTTON_LEFT_TRIGGER = 100, // Custom
            GAMEPAD_BUTTON_RIGHT_TRIGGER = 101, // Custom

            GAMEPAD_BUTTON_MIDDLE_LEFT = SDL_CONTROLLER_BUTTON_BACK,
            GAMEPAD_BUTTON_MIDDLE = SDL_CONTROLLER_BUTTON_GUIDE,
            GAMEPAD_BUTTON_MIDDLE_RIGHT = SDL_CONTROLLER_BUTTON_START,

            GAMEPAD_BUTTON_LEFT_FACE_UP = SDL_CONTROLLER_BUTTON_DPAD_UP,
            GAMEPAD_BUTTON_LEFT_FACE_RIGHT = SDL_CONTROLLER_BUTTON_DPAD_RIGHT,
            GAMEPAD_BUTTON_LEFT_FACE_DOWN = SDL_CONTROLLER_BUTTON_DPAD_DOWN,
            GAMEPAD_BUTTON_LEFT_FACE_LEFT = SDL_CONTROLLER_BUTTON_DPAD_LEFT,

            GAMEPAD_BUTTON_LEFT_THUMB = SDL_CONTROLLER_BUTTON_LEFTSTICK,
            GAMEPAD_BUTTON_RIGHT_THUMB = SDL_CONTROLLER_BUTTON_RIGHTSTICK,

            // These does nothing
            /* SDL_CONTROLLER_BUTTON_MISC1 */
            /* SDL_CONTROLLER_BUTTON_PADDLE1 */
            /* SDL_CONTROLLER_BUTTON_PADDLE2 */
            /* SDL_CONTROLLER_BUTTON_PADDLE3 */
            /* SDL_CONTROLLER_BUTTON_PADDLE4 */
            /* SDL_CONTROLLER_BUTTON_TOUCHPAD */
        };
    }
}
}
